### ISSUE TITLE
Standardize FreeSWITCH Configuration for Docker Environment and Implement Outbound Calling

### ISSUE THREAD

**Issue by ldraney** [intelligent-staffing-systems/freeswitch-server#1]
## USER STORY
AS A FreeSWITCH developer working on an AI appointment setting system
I WANT to set up a clear, consistent, and customizable FreeSWITCH configuration within our Docker environment
SO THAT we can reliably initiate outbound calls and integrate with our AI system

## ACCEPTANCE CRITERIA
* [ ] Identify the active FreeSWITCH configuration used in the Docker container
* [ ] Create a custom SIP profile for outbound calling
* [ ] Set up a basic dialplan for handling outbound calls
* [ ] Implement a Lua script for initiating calls
* [ ] Ensure the custom configuration is properly integrated into the Docker build process
* [ ] Verify that the custom configuration is being used when the container runs
* [ ] Successfully initiate a test call using the new configuration and Lua script

### Context:
Our project uses FreeSWITCH within a Docker container as part of a microservices architecture for an AI appointment setting system. We've noticed multiple `sip_profiles` directories in our FreeSWITCH source, causing confusion about which configuration is actually being used.

### Current Directory Structure:
```
./freeswitch-src/conf/testing/sip_profiles
./freeswitch-src/conf/vanilla/sip_profiles
./freeswitch-src/conf/minimal/sip_profiles
./freeswitch-src/conf/rayo/sip_profiles
./freeswitch-src/conf/insideout/sip_profiles
```

### Action Plan:
1. Examine the Dockerfile and docker-compose.yml to identify which configuration is being copied or mounted.
2. Create a custom configuration based on the identified base (e.g., vanilla).
3. Modify the Dockerfile or docker-compose.yml to use this custom configuration.
4. Implement the necessary changes in the custom configuration:
   - Create outbound SIP profile
   - Set up basic dialplan
   - Add Lua script for call initiation
5. Build and run the Docker container with the new configuration.
6. Verify the active configuration inside the running container.
7. Test the setup by initiating a call using the Lua script.

### Diagram:
```
+-------------------+
|  Docker Container |
|  +-------------+  |
|  | FreeSWITCH  |  |
|  |  +--------+ |  |
|  |  | Custom | |  |
|  |  | Config | |  |
|  |  +--------+ |  |
|  +-------------+  |
+-------------------+
         |
         | Outbound Call
         v
  [SIP Provider]
         |
         v
  [Phone Network]
```

This setup will ensure a clear and consistent configuration for our FreeSWITCH instance, providing a solid foundation for further development of our AI appointment setting system.
